#!/usr/bin/env python3
"""Generate drift-checked reference docs from live AEGIS surfaces."""

from __future__ import annotations

import argparse
import copy
import difflib
import sys
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
GENERATED = "<!-- generated by scripts/generate_reference_docs.py; do not edit by hand -->"


def _repo_imports() -> None:
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))


def _markdown_table(headers: list[str], rows: Iterable[list[str]]) -> str:
    out = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    for row in rows:
        out.append("| " + " | ".join(_escape_cell(cell) for cell in row) + " |")
    return "\n".join(out) + "\n"


def _escape_cell(value: object) -> str:
    return str(value or "").replace("|", "\\|").replace("\n", " ").strip()


def _choice_help(parser: argparse.ArgumentParser) -> dict[str, str]:
    for action in getattr(parser, "_actions", []):
        if isinstance(action, argparse._SubParsersAction):
            return {choice.dest: str(choice.help or "") for choice in action._choices_actions}
    return {}


def _iter_cli_commands(parser: argparse.ArgumentParser, prefix: str = "aegis"):
    helps = _choice_help(parser)
    for action in getattr(parser, "_actions", []):
        if not isinstance(action, argparse._SubParsersAction):
            continue
        for name, subparser in sorted(action.choices.items()):
            help_text = helps.get(name, "")
            if help_text == argparse.SUPPRESS:
                continue
            command = f"{prefix} {name}"
            usage = subparser.format_usage().replace("usage: ", "").strip()
            yield {
                "command": command,
                "help": help_text or str(subparser.description or ""),
                "usage": usage,
            }
            yield from _iter_cli_commands(subparser, command)


def generate_cli_reference() -> str:
    _repo_imports()
    from aegis.cli.main import build_parser

    parser = build_parser()
    rows = [
        [item["command"], item["help"], f"`{item['usage']}`"]
        for item in _iter_cli_commands(parser)
    ]
    return (
        f"{GENERATED}\n"
        "# CLI Reference\n\n"
        "Generated from `aegis.cli.main.build_parser()`.\n\n"
        + _markdown_table(["Command", "Summary", "Usage"], rows)
    )


def generate_slash_reference() -> str:
    _repo_imports()
    from aegis.cli.repl import SLASH_COMMANDS

    rows = [
        [cmd.name, cmd.group, cmd.summary, cmd.usage or cmd.name]
        for cmd in sorted(SLASH_COMMANDS, key=lambda item: (item.group, item.name))
    ]
    return (
        f"{GENERATED}\n"
        "# Slash Commands\n\n"
        "Generated from `aegis.cli.repl.SLASH_COMMANDS`.\n\n"
        + _markdown_table(["Command", "Group", "Summary", "Usage"], rows)
    )


def generate_api_routes() -> str:
    _repo_imports()
    from fastapi.routing import APIRoute, APIWebSocketRoute

    from aegis.config import Config, DEFAULT_CONFIG
    from aegis.dashboard_fastapi import create_app

    app = create_app(Config(copy.deepcopy(DEFAULT_CONFIG)))
    rows: list[list[str]] = []
    for route in app.router.routes:
        path = str(getattr(route, "path", "") or "")
        if not path.startswith("/api") and path not in {"/", "/health"}:
            continue
        if isinstance(route, APIRoute):
            methods = ", ".join(sorted(route.methods or []))
            rows.append([path, methods, route.name or ""])
        elif isinstance(route, APIWebSocketRoute):
            rows.append([path, "WEBSOCKET", route.name or ""])
    rows.sort(key=lambda row: (row[0], row[1], row[2]))
    return (
        f"{GENERATED}\n"
        "# API Routes\n\n"
        "Generated from `aegis.dashboard_fastapi.create_app()` using default config.\n\n"
        + _markdown_table(["Path", "Methods", "Name"], rows)
    )


def generate_tools_reference() -> str:
    _repo_imports()
    from aegis.tools.registry import default_registry

    rows = []
    for tool in sorted(default_registry(include_plugins=False).all(), key=lambda item: (item.toolset, item.name)):
        meta = tool.metadata()
        params = tool.schema().get("parameters", {})
        properties = params.get("properties") if isinstance(params, dict) else {}
        rows.append([
            tool.name,
            tool.toolset,
            ", ".join(tool.groups or []),
            meta.get("risk_level", ""),
            str(meta.get("schema_hash", ""))[:12],
            ", ".join(sorted(properties)) if isinstance(properties, dict) else "",
            (tool.description or "").splitlines()[0],
        ])
    return (
        f"{GENERATED}\n"
        "# Tools Reference\n\n"
        "Generated from the built-in tool registry without personal plugins.\n\n"
        + _markdown_table(["Tool", "Toolset", "Groups", "Risk", "Schema", "Parameters", "Summary"], rows)
    )


def generated_docs() -> dict[Path, str]:
    return {
        DOCS / "cli-reference.md": generate_cli_reference(),
        DOCS / "slash-commands.md": generate_slash_reference(),
        DOCS / "api-routes.md": generate_api_routes(),
        DOCS / "tools-reference.md": generate_tools_reference(),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate or check AEGIS reference docs.")
    parser.add_argument("--check", action="store_true", help="fail if generated docs are stale")
    args = parser.parse_args(argv)
    stale: list[Path] = []
    for path, content in generated_docs().items():
        if args.check:
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current != content:
                stale.append(path)
                diff = difflib.unified_diff(
                    current.splitlines(),
                    content.splitlines(),
                    fromfile=str(path),
                    tofile=f"{path} (generated)",
                    lineterm="",
                )
                print("\n".join(list(diff)[:80]))
        else:
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        print("Generated docs are stale. Run: python scripts/generate_reference_docs.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
